name: Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            data_separator: ":"
            tkdnd_install_sript: "bash ./gui/install_tkdnd.sh"
          - os: windows-latest
            data_separator: ";"
            tkdnd_install_sript: "./gui/install_tkdnd.bat"
            site_packages: "C:\hostedtoolcache\windows\Python\3.7.9\x64"
          - os: macos-latest
            data_separator: ":"
            tkdnd_install_sript: "bash ./gui/install_tkdnd.sh"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Echoing
      run: |
        echo "$(python -c 'import site; print(site.getsitepackages()[0])'), $(python -m site --user-site)"
