name: Lint

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Move the dependencies
        run: mv .venv /home/runner/work/_temp/_github_workflow
      - name: Lint
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: false
          LINTER_RULES_PATH: .
          PYTHONPATH: "/github/workspace/:\
                        /github/workflow/.venv/lib/python3.7/site-packages"
